[package]
name = "test_spv"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
debug = 2

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "^1.0"
